### ISSUE TITLE
Support PageListSelect in ProcessWire's Page Export feature

### ISSUE THREAD

**Issue by jlahijani** [Toutouwai/PageListSelectMultipleQuickly#3]
ProcessWire's page export feature has an option called 'Pages that I select' which allows you to hand-pick which pages you want it to specifically export.  The page chooser there is PageListSelect, but it does not get enhanced with this quickly module.  Is it possible to add support there as well?

**Comment by Toutouwai** [comment]
Added support for this in v0.1.2 just released.
